import React,{useEffect,useMemo,useRef,useState}from"react";
import{ArrowDown,ArrowUp,Download,FileDown,FolderOpen,ImagePlus,Plus,Printer,RotateCcw,Save,ShieldCheck,Trash2,X}from"lucide-react";
import{Document,Packer,Paragraph,TextRun,HeadingLevel,Table,TableCell,TableRow,WidthType,ShadingType,AlignmentType,ImageRun,PageBreak}from"docx";
const id=()=>crypto.randomUUID?.()||Date.now()+"-"+Math.random();
const emptyStep=()=>({id:id(),title:"",instruction:"",check:"",caption:"",image:""});
const initial={title:"Monthly Reporting Procedure",owner:"Regulatory Reporting / Revenue Requirement",systems:"Excel / Oracle Fusion / FDI",frequency:"Monthly",version:"Draft 0.1",preparedBy:"",purpose:"",scope:"",prerequisites:"Confirm access to required systems and source files.\nUse the current approved template.\nDo not overwrite approved prior-period records.",controls:"",troubleshooting:"",retention:"Save the final output using the approved naming convention.\nRetain source reports, reconciliations, explanations, and review evidence.\nObtain owner and reviewer approval before publishing.",steps:[emptyStep()]};
const lines=t=>String(t||"").split(/\n+/).map(x=>x.trim()).filter(Boolean);
const safe=s=>(s||"SOP").replace(/[^a-z0-9_-]+/gi,"_");
function Field({label,value,onChange,area=false,wide=false,placeholder=""}){return <label className={wide?"field wide":"field"}><span>{label}</span>{area?<textarea value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/>:<input value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/>}</label>}
export default function App(){
 const[data,setData]=useState(()=>{try{return JSON.parse(localStorage.getItem("sop-project"))||initial}catch{return initial}});const[preview,setPreview]=useState(false);const[message,setMessage]=useState("");const loadRef=useRef();
 useEffect(()=>localStorage.setItem("sop-project",JSON.stringify(data)),[data]);
 const set=(key,value)=>setData(d=>({...d,[key]:value}));const valid=useMemo(()=>data.steps.filter(s=>s.instruction.trim()),[data.steps]);
 const stepPatch=(sid,patch)=>setData(d=>({...d,steps:d.steps.map(s=>s.id===sid?{...s,...patch}:s)}));
 const move=(i,n)=>setData(d=>{const a=[...d.steps],j=i+n;if(j<0||j>=a.length)return d;[a[i],a[j]]=[a[j],a[i]];return{...d,steps:a}});
 const image=(sid,file)=>{if(!file?.type.startsWith("image/"))return;const r=new FileReader();r.onload=()=>stepPatch(sid,{image:r.result});r.readAsDataURL(file)};
 const download=(blob,name)=>{const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
 const saveProject=()=>download(new Blob([JSON.stringify(data,null,2)],{type:"application/json"}),safe(data.title)+".sop.json");
 const loadProject=file=>{const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result);if(!Array.isArray(x.steps))throw Error();setData(x);setMessage("Project loaded.")}catch{setMessage("That file is not a valid SOP project.")}};r.readAsText(file)};
 const dataUrlBytes=async u=>new Uint8Array(await(await fetch(u)).arrayBuffer());
 const exportDocx=async()=>{setMessage("Creating Word document...");try{const children=[];
  children.push(new Paragraph({heading:HeadingLevel.TITLE,children:[new TextRun({text:data.title||"Untitled Procedure",bold:true,color:"17365D"})]}),new Paragraph({children:[new TextRun({text:"Internal Use | Draft for review",italics:true,color:"666666"})]}));
  const meta=[["Owner",data.owner,"Version",data.version],["Systems",data.systems,"Frequency",data.frequency],["Prepared by",data.preparedBy||"Not provided","Status","Draft for review"]];
  children.push(new Table({width:{size:100,type:WidthType.PERCENTAGE},rows:meta.map(r=>new TableRow({children:r.map((v,i)=>new TableCell({shading:i%2===0?{fill:"D9EAF7",type:ShadingType.CLEAR}:undefined,children:[new Paragraph({children:[new TextRun({text:v||"Not provided",bold:i%2===0})]})]}))}))}));
  const section=(n,title,text)=>{children.push(new Paragraph({heading:HeadingLevel.HEADING_1,children:[new TextRun(n+". "+title)]}),new Paragraph(text||"Not provided"))};
  section(1,"Purpose",data.purpose);section(2,"Scope",data.scope);children.push(new Paragraph({heading:HeadingLevel.HEADING_1,text:"3. Prerequisites and references"}),...lines(data.prerequisites).map(x=>new Paragraph({text:x,bullet:{level:0}})),new Paragraph({heading:HeadingLevel.HEADING_1,text:"4. Step-by-step procedure"}));
  for(let i=0;i<valid.length;i++){const s=valid[i];children.push(new Paragraph({heading:HeadingLevel.HEADING_2,text:`Step ${i+1}: ${s.title||"Complete procedure step"}`}),...lines(s.instruction).map(x=>new Paragraph(x)));if(s.image){const bytes=await dataUrlBytes(s.image);children.push(new Paragraph({alignment:AlignmentType.CENTER,children:[new ImageRun({data:bytes,transformation:{width:600,height:360}})]}),new Paragraph({alignment:AlignmentType.CENTER,children:[new TextRun({text:s.caption||`Figure ${i+1}. Screenshot supporting step ${i+1}.`,italics:true,color:"666666"})]}))}children.push(new Paragraph({children:[new TextRun({text:"Completion check: ",bold:true,color:"047857"}),new TextRun(s.check||"Confirm successful completion before continuing.")]}))}
  section(5,"Controls, validation, and exceptions",data.controls);children.push(new Paragraph({heading:HeadingLevel.HEADING_1,text:"6. Troubleshooting"}),...(lines(data.troubleshooting).length?lines(data.troubleshooting).map(x=>new Paragraph({text:x,bullet:{level:0}})):[new Paragraph("No troubleshooting items documented.")]),new Paragraph({heading:HeadingLevel.HEADING_1,text:"7. Output and retention"}),...lines(data.retention).map(x=>new Paragraph({text:x,bullet:{level:0}})),new Paragraph({heading:HeadingLevel.HEADING_1,text:"8. Revision history"}),new Paragraph(`${data.version||"Draft 0.1"}: Initial draft created from entered steps and screenshots.`));
  const doc=new Document({sections:[{properties:{},children}]});download(await Packer.toBlob(doc),safe(data.title)+".docx");setMessage("Word document downloaded.")}catch(e){console.error(e);setMessage("Word export failed. Try smaller PNG or JPG screenshots.")}};
 return <><header><div className="brand"><ShieldCheck/> DESKTOP PROCEDURE STUDIO</div><h1>SOP Generator Pro</h1><p>Build, save, reopen, print, and export desktop procedures as real Word documents.</p></header><main><section className="editor">
  <div className="toolbar"><button onClick={saveProject}><Save/>Save project</button><button onClick={()=>loadRef.current.click()}><FolderOpen/>Open project</button><input ref={loadRef} hidden type="file" accept="application/json,.json" onChange={e=>loadProject(e.target.files[0])}/><button className="danger" onClick={()=>{if(confirm("Clear this SOP?")){setData({...initial,steps:[emptyStep()]});setPreview(false)}}}><RotateCcw/>Start over</button></div>
  {message&&<div className="message">{message}</div>}
  <div className="card"><h2>1. Document control</h2><div className="grid"><Field wide label="Procedure title" value={data.title} onChange={v=>set("title",v)}/><Field label="Owner / team" value={data.owner} onChange={v=>set("owner",v)}/><Field label="Systems / tools" value={data.systems} onChange={v=>set("systems",v)}/><Field label="Frequency" value={data.frequency} onChange={v=>set("frequency",v)}/><Field label="Version" value={data.version} onChange={v=>set("version",v)}/><Field wide label="Prepared by" value={data.preparedBy} onChange={v=>set("preparedBy",v)}/><Field wide area label="Purpose" value={data.purpose} onChange={v=>set("purpose",v)}/><Field wide area label="Scope" value={data.scope} onChange={v=>set("scope",v)}/><Field wide area label="Prerequisites, one per line" value={data.prerequisites} onChange={v=>set("prerequisites",v)}/></div></div>
  <div className="card"><h2>2. Procedure steps and screenshots</h2>{data.steps.map((s,i)=><div className="stepedit" key={s.id}><div className="stepbar"><b>Step {i+1}</b><span><button title="Move up" onClick={()=>move(i,-1)}><ArrowUp/></button><button title="Move down" onClick={()=>move(i,1)}><ArrowDown/></button><button title="Delete" className="icon danger" onClick={()=>setData(d=>({...d,steps:d.steps.length===1?[emptyStep()]:d.steps.filter(x=>x.id!==s.id)}))}><Trash2/></button></span></div><input value={s.title} onChange={e=>stepPatch(s.id,{title:e.target.value})} placeholder="Step title"/><textarea value={s.instruction} onChange={e=>stepPatch(s.id,{instruction:e.target.value})} placeholder="Describe exactly what to click, enter, select, compare, or verify."/><input value={s.check} onChange={e=>stepPatch(s.id,{check:e.target.value})} placeholder="Completion check or expected result"/><label className="drop">{s.image?<img src={s.image}/>:<><ImagePlus/><span>Select screenshot</span></>}<input hidden type="file" accept="image/*" onChange={e=>image(s.id,e.target.files[0])}/></label>{s.image&&<div className="caption"><input value={s.caption} onChange={e=>stepPatch(s.id,{caption:e.target.value})} placeholder="Screenshot caption"/><button onClick={()=>stepPatch(s.id,{image:"",caption:""})}><X/></button></div>}</div>)}<button className="full" onClick={()=>setData(d=>({...d,steps:[...d.steps,emptyStep()]}))}><Plus/>Add another step</button></div>
  <div className="card"><h2>3. Controls and support</h2><Field wide area label="Controls, validation, exceptions, and escalation" value={data.controls} onChange={v=>set("controls",v)}/><Field wide area label="Troubleshooting, one item per line" value={data.troubleshooting} onChange={v=>set("troubleshooting",v)}/><Field wide area label="Output and retention, one item per line" value={data.retention} onChange={v=>set("retention",v)}/></div>
  <button className="primary full" disabled={!valid.length} onClick={()=>setPreview(true)}><Eye/>Generate preview</button>
 </section><aside><div className="previewHead"><b>SOP preview</b><span><button disabled={!valid.length} onClick={exportDocx}><FileDown/>Word</button><button disabled={!valid.length} onClick={()=>window.print()}><Printer/>Print/PDF</button></span></div><div className="paper">{!preview?<div className="empty"><FileDown/><p>Complete a step, then generate the preview.</p></div>:<article><h1>{data.title}</h1><p className="muted">Internal Use | Draft for review</p><table><tbody><tr><th>Owner</th><td>{data.owner}</td><th>Version</th><td>{data.version}</td></tr><tr><th>Systems</th><td>{data.systems}</td><th>Frequency</th><td>{data.frequency}</td></tr></tbody></table><h2>1. Purpose</h2><p>{data.purpose||"Not provided"}</p><h2>2. Scope</h2><p>{data.scope||"Not provided"}</p><h2>3. Prerequisites</h2><ul>{lines(data.prerequisites).map((x,i)=><li key={i}>{x}</li>)}</ul><h2>4. Step-by-step procedure</h2>{valid.map((s,i)=><div className="sopstep" key={s.id}><h3>Step {i+1}: {s.title||"Complete procedure step"}</h3>{lines(s.instruction).map((x,j)=><p key={j}>{x}</p>)}{s.image&&<><img src={s.image}/><p className="muted center">{s.caption||`Figure ${i+1}`}</p></>}<div className="check"><b>Completion check:</b> {s.check||"Confirm successful completion before continuing."}</div></div>)}<h2>5. Controls and exceptions</h2><div className="warning">{data.controls||"Not provided"}</div><h2>6. Troubleshooting</h2><ul>{lines(data.troubleshooting).map((x,i)=><li key={i}>{x}</li>)}</ul><h2>7. Output and retention</h2><ul>{lines(data.retention).map((x,i)=><li key={i}>{x}</li>)}</ul><h2>8. Revision history</h2><p><b>{data.version}:</b> Initial draft.</p></article>}</div></aside></main></>}
