(function(){'use strict';
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])), lines=s=>String(s||'').split(/\n+/).map(x=>x.trim()).filter(Boolean), id=()=>crypto.randomUUID?.()||Date.now()+'-'+Math.random();
const blankStep=()=>({id:id(),title:'',instruction:'',check:'',caption:'',image:''});const blankSop=()=>({id:id(),title:'Untitled SOP',owner:'',systems:'',frequency:'',version:'Draft 0.1',prepared:'',purpose:'',scope:'',prereq:'',controls:'',trouble:'',retention:'',steps:[blankStep()],createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()});
const fields=['title','owner','systems','frequency','version','prepared','purpose','scope','prereq','controls','trouble','retention'];let current=blankSop(),timer;
const library=()=>{try{return JSON.parse(localStorage.getItem('sop-library-v1'))||[]}catch{return[]}};const writeLibrary=x=>localStorage.setItem('sop-library-v1',JSON.stringify(x));
function readForm(){fields.forEach(k=>current[k]=$('#'+k).value);current.updatedAt=new Date().toISOString();return current}function fillForm(){fields.forEach(k=>$('#'+k).value=current[k]||'');renderSteps();$('#status').textContent='Opened: '+(current.title||'Untitled SOP')}
function persist(){readForm();let a=library(),i=a.findIndex(x=>x.id===current.id);if(i<0)a.unshift(current);else a[i]=current;writeLibrary(a);localStorage.setItem('sop-current-id',current.id);$('#status').textContent='Saved '+new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'});renderHistory()}
function queue(){clearTimeout(timer);timer=setTimeout(persist,350)}
function renderSteps(){const host=$('#steps');host.innerHTML='';current.steps.forEach((s,i)=>{const e=document.createElement('div');e.className='step';e.innerHTML=`<div class="stephead"><strong>Step ${i+1}</strong><span><button class="up">Up</button><button class="down">Down</button><button class="delete">Delete</button></span></div><input class="st" placeholder="Step title"><textarea class="si" placeholder="Describe exactly what to click, enter, select, compare, or verify."></textarea><input class="sc" placeholder="Completion check"><label class="upload">${s.image?'<img>':'Select screenshot'}<input hidden type="file" accept="image/*"></label>${s.image?'<div class="caption"><input placeholder="Screenshot caption"><button class="remove">Remove</button></div>':''}`;e.querySelector('.st').value=s.title;e.querySelector('.si').value=s.instruction;e.querySelector('.sc').value=s.check;e.querySelector('.st').oninput=x=>{s.title=x.target.value;queue()};e.querySelector('.si').oninput=x=>{s.instruction=x.target.value;queue()};e.querySelector('.sc').oninput=x=>{s.check=x.target.value;queue()};e.querySelector('.up').onclick=()=>move(i,-1);e.querySelector('.down').onclick=()=>move(i,1);e.querySelector('.delete').onclick=()=>{current.steps=current.steps.length===1?[blankStep()]:current.steps.filter((_,j)=>j!==i);renderSteps();persist()};e.querySelector('input[type=file]').onchange=x=>{const f=x.target.files[0];if(!f?.type.startsWith('image/'))return;const r=new FileReader();r.onload=()=>{s.image=r.result;renderSteps();persist()};r.readAsDataURL(f)};if(s.image){e.querySelector('img').src=s.image;e.querySelector('.caption input').value=s.caption;e.querySelector('.caption input').oninput=x=>{s.caption=x.target.value;queue()};e.querySelector('.remove').onclick=()=>{s.image='';s.caption='';renderSteps();persist()}}host.appendChild(e)})}
function move(i,d){const j=i+d;if(j<0||j>=current.steps.length)return;[current.steps[i],current.steps[j]]=[current.steps[j],current.steps[i]];renderSteps();persist()}
function plan(){const p=[];if(current.purpose.trim())p.push(['Purpose','text',current.purpose]);if(current.scope.trim())p.push(['Scope','text',current.scope]);if(lines(current.prereq).length)p.push(['Prerequisites and references','list',lines(current.prereq)]);p.push(['Step-by-step procedure','steps',current.steps.filter(s=>s.title.trim()||s.instruction.trim()||s.image)]);if(current.controls.trim())p.push(['Controls, validation, and exceptions','text',current.controls]);if(lines(current.trouble).length)p.push(['Troubleshooting','list',lines(current.trouble)]);if(lines(current.retention).length)p.push(['Output and retention','list',lines(current.retention)]);p.push(['Revision history','revision',current.version]);return p.map(x=>({title:x[0],kind:x[1],value:x[2]}))}
function preview(){readForm();const valid=current.steps.filter(s=>s.title.trim()||s.instruction.trim()||s.image);if(!valid.length)return alert('Add at least one procedure step.');let body='';plan().forEach((p,n)=>{body+=`<h2>${n+1}. ${esc(p.title)}</h2>`;if(p.kind==='text')body+=`<p>${esc(p.value)}</p>`;if(p.kind==='list')body+=`<ul>${p.value.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`;if(p.kind==='revision')body+=`<p><b>${esc(p.value)}:</b> Initial draft.</p>`;if(p.kind==='steps')body+=p.value.map((s,i)=>`<section><h3>Step ${i+1}: ${esc(s.title||'Procedure step')}</h3>${lines(s.instruction).map(x=>`<p>${esc(x)}</p>`).join('')}${s.image?`<img src="${s.image}"><p>${esc(s.caption)}</p>`:''}${s.check?`<div class="check"><b>Completion check:</b> ${esc(s.check)}</div>`:''}</section>`).join('')});$('#preview').innerHTML=`<article><h1>${esc(current.title)}</h1><table><tr><th>Owner</th><td>${esc(current.owner)}</td><th>Version</th><td>${esc(current.version)}</td></tr></table>${body}</article>`;persist()}
function renderHistory(){const host=$('#historyList'),a=library();host.innerHTML=a.length?'':'<p>No saved SOPs yet.</p>';a.forEach(s=>{const r=document.createElement('div');r.className='historyRow';r.innerHTML=`<div><b>${esc(s.title||'Untitled SOP')}</b><div class="historyMeta">Updated ${new Date(s.updatedAt).toLocaleString()}</div></div><div class="historyActions"><button class="open">Open</button><button class="duplicate">Duplicate</button><button class="rename">Rename</button><button class="delete">Delete</button></div>`;r.querySelector('.open').onclick=()=>{current=s;fillForm();$('#historyModal').classList.add('hidden');localStorage.setItem('sop-current-id',s.id)};r.querySelector('.duplicate').onclick=()=>{const c=JSON.parse(JSON.stringify(s));c.id=id();c.title=(c.title||'Untitled SOP')+' Copy';c.createdAt=c.updatedAt=new Date().toISOString();const x=library();x.unshift(c);writeLibrary(x);renderHistory()};r.querySelector('.rename').onclick=()=>{const name=prompt('New SOP name',s.title);if(!name)return;s.title=name;s.updatedAt=new Date().toISOString();const x=library(),i=x.findIndex(y=>y.id===s.id);x[i]=s;writeLibrary(x);if(current.id===s.id){current=s;fillForm()}renderHistory()};r.querySelector('.delete').onclick=()=>{if(!confirm('Delete this saved SOP?'))return;writeLibrary(library().filter(x=>x.id!==s.id));if(current.id===s.id){current=blankSop();fillForm();persist()}renderHistory()};host.appendChild(r)})}
function downloadProject(){persist();const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(current,null,2)],{type:'application/json'}));a.download=(current.title||'SOP').replace(/[^a-z0-9_-]+/gi,'_')+'.sop.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function openProject(file){const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result);if(!Array.isArray(x.steps))throw Error();x.id=id();x.createdAt=x.createdAt||new Date().toISOString();x.updatedAt=new Date().toISOString();current=x;fillForm();persist()}catch{alert('That is not a valid SOP project file.')}};r.readAsText(file)}
async function word(){preview();const mod=await import('./word-export.js');await mod.exportWord({...current,sections:plan()})}
$('#addStep').onclick=()=>{current.steps.push(blankStep());renderSteps();persist()};$('#generate').onclick=preview;$('#word').onclick=word;$('#newSop').onclick=()=>{if(confirm('Start a new SOP? Your current SOP is already saved in My SOPs.')){persist();current=blankSop();fillForm();persist();$('#preview').innerHTML='<div class="empty">Enter at least one procedure step, then generate the preview.</div>'}};$('#saveProject').onclick=downloadProject;$('#openProject').onclick=()=>$('#projectFile').click();$('#projectFile').onchange=e=>e.target.files[0]&&openProject(e.target.files[0]);$('#historyButton').onclick=()=>{$('#historyModal').classList.remove('hidden');renderHistory()};$('#closeHistory').onclick=()=>$('#historyModal').classList.add('hidden');fields.forEach(k=>$('#'+k).addEventListener('input',queue));
const a=library(),currentId=localStorage.getItem('sop-current-id'),found=a.find(x=>x.id===currentId);current=found||a[0]||blankSop();fillForm();persist();
})();
