export async function exportWord(model){
  const docx=await import('https://cdn.jsdelivr.net/npm/docx@9.7.1/+esm');
  const {Document,Packer,Paragraph,TextRun,HeadingLevel,Table,TableCell,TableRow,WidthType,ShadingType,AlignmentType,ImageRun}=docx;
  const lines=s=>String(s||'').split(/\n+/).map(x=>x.trim()).filter(Boolean);const bytes=async u=>new Uint8Array(await(await fetch(u)).arrayBuffer());const safe=s=>(s||'SOP').replace(/[^a-z0-9_-]+/gi,'_');const c=[];
  c.push(new Paragraph({heading:HeadingLevel.TITLE,children:[new TextRun({text:model.title||'Untitled Procedure',bold:true,color:'17365D'})]}),new Paragraph({children:[new TextRun({text:'Internal Use | Draft for review',italics:true,color:'666666'})]}));
  const rows=[['Owner',model.owner||'Not provided','Version',model.version||'Not provided'],['Systems',model.systems||'Not provided','Frequency',model.frequency||'Not provided']];if((model.prepared||'').trim())rows.push(['Prepared by',model.prepared,'Status','Draft for review']);
  c.push(new Table({width:{size:100,type:WidthType.PERCENTAGE},rows:rows.map(r=>new TableRow({children:r.map((x,i)=>new TableCell({shading:i%2===0?{fill:'D9EAF7',type:ShadingType.CLEAR}:undefined,children:[new Paragraph({children:[new TextRun({text:x,bold:i%2===0})]})]}))}))}));
  for(let n=0;n<model.sections.length;n++){const p=model.sections[n];c.push(new Paragraph({heading:HeadingLevel.HEADING_1,text:(n+1)+'. '+p.title}));if(p.kind==='text')c.push(new Paragraph(p.value));if(p.kind==='list')c.push(...p.value.map(x=>new Paragraph({text:x,bullet:{level:0}})));if(p.kind==='revision')c.push(new Paragraph((p.value||'Draft 0.1')+': Initial draft.'));if(p.kind==='steps'){for(let i=0;i<p.value.length;i++){const s=p.value[i];c.push(new Paragraph({heading:HeadingLevel.HEADING_2,text:'Step '+(i+1)+': '+(s.title||'Procedure step')}));if(lines(s.instruction).length)c.push(...lines(s.instruction).map(x=>new Paragraph(x)));if(s.image)c.push(new Paragraph({alignment:AlignmentType.CENTER,children:[new ImageRun({data:await bytes(s.image),transformation:{width:600,height:360}})]}),new Paragraph({alignment:AlignmentType.CENTER,children:[new TextRun({text:s.caption||'Figure '+(i+1)+'. Screenshot supporting this step.',italics:true,color:'666666'})]}));if((s.check||'').trim())c.push(new Paragraph({children:[new TextRun({text:'Completion check: ',bold:true,color:'087A55'}),new TextRun(s.check)]}))}}}
  const blob=await Packer.toBlob(new Document({sections:[{children:c}]}));const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=safe(model.title)+'.docx';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1000);
}
